---
version: '2'

networks:
  salt:

services:
  master:
    networks:
        - salt
    image: ksator/saltstack_master_junos_syslog_engine_docker:latest
    container_name: master
    ports:
        - "516:516/udp"
        - "4505:4505"
        - "4506:4506"
        - "5001:5001"
    volumes:
        - ./saltstack/master:/etc/salt/master
        - ./saltstack/pillar/.:/srv/pillar/
        - ./saltstack/salt/.:/srv/salt/
    tty: true

  minion1:
    networks:
        - salt
    image: ksator/saltstack_minion_junos_modules_docker:latest
    container_name: minion1
    ports:
        - "4605:4505"
        - "4606:4506"
    volumes:
        - ./saltstack/minion:/etc/salt/minion
        - ./saltstack/proxy:/etc/salt/proxy
    tty: true
    depends_on:
        - "master"

  influxdb:
    image: influxdb:1.7.2
    container_name: influxdb
    expose:
      - 8086
      - 8083
    networks:
      - salt

  telegraf-snmp:
    image: ksator/telegraf_with_snmp_mib
    container_name: telegraf-snmp
    volumes:
      - $PWD/configs/telegraf-snmp.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
      - "influxdb"
    networks:
      - salt


  telegraf-openconfig:
    image: telegraf:1.9.1
    container_name: telegraf-openconfig
    volumes:
      - $PWD/configs/telegraf-openconfig.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
      - "influxdb"
    networks:
      - salt


  request-tracker:
    image: netsandbox/request-tracker
    container_name: request-tracker
    ports:
      - "9080:80"
    networks:
      - salt


  grafana:
    image: grafana/grafana:5.4.2
    container_name: grafana
    ports:
      - "9081:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=jcluser
      - GF_SECURITY_ADMIN_PASSWORD=Juniper!1
    volumes:
      - $PWD/configs/datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml:ro
      - $PWD/configs/dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml:ro
      - $PWD/dashboards:/var/tmp/dashboards
    depends_on:
      - "telegraf-snmp"
      - "telegraf-openconfig"
    networks:
      - salt



